package tracer

// ebpf_maps.go handles population and maintenance of eBPF maps that control
// kernel-side filtering behavior. These maps are the shared data plane between
// userspace (this tracer) and the BPF programs running in the kernel.
//
// Map categories:
//   - Network state: socket grants, hostname observations, DNS resolvers
//   - Block lists: executable names, protected file paths
//   - Control: self TGID (to skip self-generated events)

import (
	"os"

	"github.com/cilium/ebpf"

	"github.com/kondukto-io/kntrl/internal/core/domain"
	ebpfman "github.com/kondukto-io/kntrl/pkg/ebpf"
	"github.com/kondukto-io/kntrl/pkg/logger"
)

// updateAllowedHostMap writes all allowed hostnames into the BPF map as
// fixed-size 256-byte keys (NUL-padded).
func updateAllowedHostMap(allowedHostMap *ebpf.Map, arg *domain.Data) error {
	for _, host := range arg.AllowedHosts {
		var key [256]byte
		copy(key[:], host)
		if err := allowedHostMap.Put(key, uint32(1)); err != nil {
			return err
		}
	}
	return nil
}

// populateDNSServerMap replaces the DNS exception, including on policy reload.
func populateDNSServerMap(ebpfClient *ebpfman.EBPF, cmddata *domain.Data) error {
	m, err := getRequiredMap(ebpfClient, domain.EBPFCollectionMapDNSResolvers)
	if err != nil {
		return err
	}
	if err := clearMap(m); err != nil {
		return err
	}
	for _, ip := range cmddata.AllowedDNSServers {
		key := domain.DNSResolverKey{Family: 10}
		if v4 := ip.To4(); v4 != nil {
			key.Family = 2
			copy(key.Address[:], v4)
		} else {
			copy(key.Address[:], ip.To16())
		}
		if err := m.Put(key, uint32(1)); err != nil {
			return err
		}
	}
	return nil
}

// clearMap revokes grants rather than allowing stale permissions to survive.
func clearMap(m *ebpf.Map) error {
	for {
		key, err := m.NextKeyBytes(nil)
		if err != nil {
			return err
		}
		if key == nil {
			return nil
		}
		if err := m.Delete(key); err != nil {
			return err
		}
	}
}

// populateSelfTGIDMap writes kntrl's own PID into the BPF map so that
// kernel-side programs can drop events generated by the tracer itself,
// preventing monitoring feedback loops.
func populateSelfTGIDMap(ebpfClient *ebpfman.EBPF) {
	selfTGIDMap := ebpfClient.Collection.Maps[domain.EBPFCollectionMapSelfTGID]
	if selfTGIDMap == nil {
		return
	}
	if err := selfTGIDMap.Put(uint32(0), uint32(os.Getpid())); err != nil {
		logger.Log.Warnf("failed to set self TGID: %v", err)
	}
}

// populateBlockedExecMap writes blocked executable names (max 16 bytes each)
// into the BPF map for kernel-level process execution blocking.
func populateBlockedExecMap(ebpfClient *ebpfman.EBPF, cmddata *domain.Data) {
	blockedExecMap := ebpfClient.Collection.Maps[domain.EBPFCollectionMapBlockedExec]
	if blockedExecMap == nil || cmddata.BlockedExecutables == nil {
		return
	}
	for _, exe := range cmddata.BlockedExecutables {
		var key [16]byte
		copy(key[:], exe)
		if err := blockedExecMap.Put(key, uint32(1)); err != nil {
			logger.Log.Warnf("failed to update blocked exec map: %v", err)
		}
	}
}

// populateProtectedPathsMap writes protected file paths (max 256 bytes each)
// into the BPF map for kernel-level file write protection.
func populateProtectedPathsMap(ebpfClient *ebpfman.EBPF, cmddata *domain.Data) {
	protectedPathsMap := ebpfClient.Collection.Maps[domain.EBPFCollectionMapProtectedPaths]
	if protectedPathsMap == nil || cmddata.ProtectedPaths == nil {
		return
	}
	for _, path := range cmddata.ProtectedPaths {
		var key [256]byte
		copy(key[:], path)
		if err := protectedPathsMap.Put(key, uint32(1)); err != nil {
			logger.Log.Warnf("failed to update protected paths map: %v", err)
		}
	}
}
