# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
release:
  github:
    owner: kondukto-io
    name: kntrl
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - go mod verify
    - make generate

builds:
  - id: "kntrl"
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=readonly
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/kondukto-io/kntrl/cmd/cli.version={{.Version}} -X github.com/kondukto-io/kntrl/cmd/cli.commit={{.ShortCommit}} -X github.com/kondukto-io/kntrl/cmd/cli.buildDate={{.Date}}
    binary: >-
      {{ .ProjectName }}
      {{- if eq .Arch "amd64" }}
      {{- else if eq .Arch "386" }}_i386
      {{- else }}_{{ .Arch }}{{ end }}
      {{- if .Arm }}_v{{ .Arm }}{{ end }}
    no_unique_dist_dir: true

archives:
  - formats: [ 'binary' ]
    #strip_binary_directory: true
    name_template: >-
      {{ .Binary }}.{{ .Arch }}
    files:
      - Readme.md 
      - LICENSE

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

#dockers:
#  - image_templates:
#    - "kondukto/kntrl:latest"
#    - "kondukto/kntrl:{{ .Tag }}"
#    dockerfile: Dockerfile
#    build_flag_templates:
#    - "--pull"
#    - "--platform=linux/amd64"
#sboms:
#  - artifacts: archive
