# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - make generate

builds:
  - id: "kntrl"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/kondukto-io/kntrl/cmd/cli.version={{.Version}} -X github.com/kondukto-io/kntrl/cmd/cli.commit={{.ShortCommit}} -X github.com/kondukto-io/kntrl/cmd/cli.buildDate={{.Date}}
    binary: >-
      {{ .ProjectName }}
      {{- if eq .Arch "amd64" }}
      {{- else if eq .Arch "386" }}_i386
      {{- else }}_{{ .Arch }}{{ end }}
      {{- if .Arm }}_v{{ .Arm }}{{ end }}
    no_unique_dist_dir: true

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Binary }}
    files:
      - Readme.md 
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

#sboms:
#  - artifacts: archive
