// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package prevent

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	Egress             *ebpf.ProgramSpec `ebpf:"egress"`
	InetSockSetState   *ebpf.ProgramSpec `ebpf:"inet_sock_set_state"`
	KprobeTcpV4Connect *ebpf.ProgramSpec `ebpf:"kprobe__tcp_v4_connect"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	AllowMap         *ebpf.MapSpec `ebpf:"allow_map"`
	Ipv4ClosedEvents *ebpf.MapSpec `ebpf:"ipv4_closed_events"`
	Ipv4Events       *ebpf.MapSpec `ebpf:"ipv4_events"`
	ModeMap          *ebpf.MapSpec `ebpf:"mode_map"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	AllowMap         *ebpf.Map `ebpf:"allow_map"`
	Ipv4ClosedEvents *ebpf.Map `ebpf:"ipv4_closed_events"`
	Ipv4Events       *ebpf.Map `ebpf:"ipv4_events"`
	ModeMap          *ebpf.Map `ebpf:"mode_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.AllowMap,
		m.Ipv4ClosedEvents,
		m.Ipv4Events,
		m.ModeMap,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	Egress             *ebpf.Program `ebpf:"egress"`
	InetSockSetState   *ebpf.Program `ebpf:"inet_sock_set_state"`
	KprobeTcpV4Connect *ebpf.Program `ebpf:"kprobe__tcp_v4_connect"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.Egress,
		p.InetSockSetState,
		p.KprobeTcpV4Connect,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel_x86.o
var _BpfBytes []byte
